; mod_spamassassin - Configuration for SpamAssassin integration

[general]
; SpamAssassin is resource intensive to run, so by default, concurrent executions are restricted to prevent a flood of incoming mail
; from using all available memory.
;max_concurrent_spam_exec = 5 ; Maximum number of parallel executions of spamassassin. Default is 5, you can increase this on beefier systems to increase throughput.
