; net_tap.conf - Telocator Alphanumeric Protocol (TAP paging)

;[general]
;port=4827 ; Port on which to accept TAP connections from modem gateway (e.g. Asterisk softmodem). No default.
           ; The appropriate Softmodem call for 7E1 would be something like Softmodem(127.0.0.1,4827,v(Bell103)led(7))
           ; Arguments are BBS server (IP or hostname),port (as in the port option above),options
           ;   options = v: Bell 103 modem standard (300 bps), e = even parity, d(7) = 7 data bits
           ;   The only other relevant option to add is 'x', which enables TLS encryption between Asterisk and the BBS.
;secureport=4828 ; Port on which to accept secure TAP connections (TLS-encrypted). No default.

;[outbound] ; Configuration for outbound calls to TAP/IXO terminals, completed using the Asterisk softmodem
;amisession = ami ; Specify a specific named AMI session in mod_asterisk_ami.conf to use for establishing the outgoing call. Default is the default session (first session in mod_asterisk_ami.conf)
;dial_context=modem-outdial ; Asterisk context used for placing outbound calls, which will actually dial the paging terminal (EXTEN will be the TAP/IXO terminal number)
                            ; If necessary (i.e. on non-analog lines), this is also where you would want to set the outgoing Caller ID for the call.
;softmodem_args=127.0.0.1,4827,v(Bell103)led(7)f ; Arguments used for Softmodem application. Main difference is it includes 'f' for originate mode instead of answer mode.
                                                 ; The options here should be adjusted to match the terminating Softmodem call, as described above.
