; net_tmp.conf - TDD Message Protocol

[general]
;port=4545 ; Port on which to accept TMP connections from modem gateway (e.g. Asterisk softmodem). No default.
           ; The appropriate Softmodem call for TMP would be something like Softmodem(127.0.0.1,4545,v(baudot45))
           ; Arguments are BBS server (IP or hostname),port (as in the port option above),options
           ;   options = v: Bell 103 modem standard (300 bps), e = even parity, d(7) = 7 data bits
           ;   The only other relevant option to add is 'x', which enables TLS encryption between Asterisk and the BBS.
;secureport=4546 ; Port on which to accept secure TMP connections (TLS-encrypted). No default.
