name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo ./scripts/install_prereq.sh
          sudo make modcheck
          sudo make -j$(nproc)
          sudo make install
          sudo make samples
          sudo make tests
      - name: Run tests
        run: |
          sudo scripts/run_tests.sh
      - name: Install service
        run: |
          sudo adduser -c "BBS" bbs --disabled-password --shell /usr/sbin/nologin --gecos ""
          # Remove the bbs.log from test suite executions since that is owned by root
          sudo rm /var/log/lbbs/bbs.log
          sudo make service
  ubuntu-stable:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo ./scripts/install_prereq.sh
          sudo make modcheck
          sudo make -j$(nproc)
          sudo make install
          sudo make samples
          sudo make tests
      - name: Run tests
        run: |
          sudo scripts/run_tests.sh
      - name: Install service
        run: |
          sudo adduser -c "BBS" bbs --disabled-password --shell /usr/sbin/nologin --gecos ""
          # Remove the bbs.log from test suite executions since that is owned by root
          sudo rm /var/log/lbbs/bbs.log
          sudo make service
  without-optimization:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, without optimization
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo sed -i 's/-O3/-O0/' Makefile
          sudo ./scripts/install_prereq.sh
          sudo make modcheck
          sudo make -j$(nproc)
          sudo make install
          sudo make samples
          sudo make tests
      - name: Install service
        run: |
          sudo adduser -c "BBS" bbs --disabled-password --shell /usr/sbin/nologin --gecos ""
          sudo make service
  debian-12:
    runs-on: ubuntu-24.04
    name: Debian 12
    container: debian:12
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  debian-11:
    runs-on: ubuntu-24.04
    name: Debian 11
    container: debian:11
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  debian-10:
    runs-on: ubuntu-24.04
    name: Debian 10
    container: debian:10
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  alpine-linux:
    runs-on: ubuntu-24.04
    name: Alpine Linux
    container: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
  fedora-42:
    runs-on: ubuntu-24.04
    name: Fedora 42
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBOPENARC=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  fedora-40:
    runs-on: ubuntu-24.04
    name: Fedora 40
    container: fedora:40
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBOPENARC=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  rocky-9:
    runs-on: ubuntu-24.04
    name: Rocky Linux 9.3
    container: rockylinux:9.3
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBOPENARC=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  rocky-8:
    runs-on: ubuntu-24.04
    name: Rocky Linux 8.9
    container: rockylinux:8.9
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBOPENARC=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  opensuse:
    runs-on: ubuntu-24.04
    name: openSUSE Tumbleweed
    container: opensuse/tumbleweed
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBETPAN=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
  archlinux:
    runs-on: ubuntu-24.04
    name: Arch Linux
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          INSTALL_LIBOPENARC=0 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make -j$(nproc)
          make install
          make samples
          make tests
      - name: Run basic tests
        run: |
          tests/test -ttest_menus -ddddddddd -DDDDDDDDDD -x
# Binary fails to link due to uuid library missing in CI, but it will make all specified targets, so enumerate those
  freebsd-14:
    runs-on: ubuntu-24.04
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            ./scripts/install_prereq.sh
            gmake modcheck
            gmake modconfig
            gmake main
            gmake doors
            gmake io
            gmake modules
            gmake nets
            gmake -j$(nproc)
            gmake install
            gmake samples
            gmake tests