name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Build LBBS
       run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo ./scripts/install_prereq.sh
          sudo make modcheck
          sudo make
          sudo make install
          sudo make samples
          sudo make tests
     - name: Run tests
       run: |
          sudo tests/test -ddddddddd -DDDDDDDDDD -x
          sudo apt-get install -y valgrind
          sudo tests/test -ddddddddd -DDDDDDDDDD -ex
  ubuntu-stable:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Build LBBS
       run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list
          sudo ./scripts/install_prereq.sh
          sudo make modcheck
          sudo make
          sudo make install
          sudo make samples
          sudo make tests
     - name: Run tests
       run: |
          sudo tests/test -ddddddddd -DDDDDDDDDD -x
          sudo apt-get install -y valgrind
          sudo tests/test -ddddddddd -DDDDDDDDDD -ex
  debian-12:
    runs-on: ubuntu-24.04
    name: Debian 12
    container: debian:12
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make
          make install
          make samples
          make tests
  debian-11:
    runs-on: ubuntu-24.04
    name: Debian 11
    container: debian:11
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make
          make install
          make samples
          make tests
  debian-10:
    runs-on: ubuntu-24.04
    name: Debian 10
    container: debian:10
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          ./scripts/install_prereq.sh
          make modcheck
          make
          make install
          make samples
          make tests
  fedora-42:
    runs-on: ubuntu-24.04
    name: Fedora 42
    container: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBETPAN=1 SKIP_LIBOPENARC=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  fedora-40:
    runs-on: ubuntu-24.04
    name: Fedora 40
    container: fedora:40
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBETPAN=1 SKIP_LIBOPENARC=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  rocky-9:
    runs-on: ubuntu-24.04
    name: Rocky Linux 9.3
    container: rockylinux:9.3
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBETPAN=1 SKIP_LIBOPENARC=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  rocky-8:
    runs-on: ubuntu-24.04
    name: Rocky Linux 8.9
    container: rockylinux:8.9
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBETPAN=1 SKIP_LIBOPENARC=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  opensuse:
    runs-on: ubuntu-24.04
    name: openSUSE Tumbleweed
    container: opensuse/tumbleweed
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBETPAN=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  archlinux:
    runs-on: ubuntu-24.04
    name: Arch Linux
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        run: |
          SKIP_LIBOPENARC=1 ./scripts/install_prereq.sh
          make modcheck
          make modconfig
          make
          make install
          make samples
          make tests
  freebsd-14:
    runs-on: ubuntu-24.04
    name: FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build LBBS
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          run: |
            ./scripts/install_prereq.sh
            gmake modcheck
            gmake modconfig
            gmake
            gmake install
            gmake samples
            gmake tests